# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AJ9fesSs8FREGDyUomKojQfbUTKd3gx
"""

pip install pandas numpy matplotlib seaborn openpyxl

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("/content/sales_data.csv")

# Show basic info
print(df.head())
print(df.info())

# --------------------------
# DATA CLEANING
# --------------------------

# Remove duplicates
df = df.drop_duplicates()

# Handle missing values
df = df.dropna()

# Convert date column (FIXED)
if 'Order Date' in df.columns:
    df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True, errors='coerce')

    # Remove invalid dates
    df = df.dropna(subset=['Order Date'])

    df['Month'] = df['Order Date'].dt.month
# --------------------------
# DATA ANALYSIS
# --------------------------

# Total sales
if 'Sales' in df.columns:
    total_sales = df['Sales'].sum()
    print("Total Sales:", total_sales)

# Top products
if 'Product' in df.columns:
    top_products = df.groupby('Product')['Sales'].sum().sort_values(ascending=False).head(10)
    print("\nTop Products:\n", top_products)

# Monthly sales
if 'Month' in df.columns:
    monthly_sales = df.groupby('Month')['Sales'].sum()
    print("\nMonthly Sales:\n", monthly_sales)

# Save cleaned data
df.to_csv("cleaned_sales_data.csv", index=False)

import matplotlib.pyplot as plt

# --------------------------
# VISUALIZATIONS
# --------------------------

# Top 10 Products Chart
if 'Product' in df.columns:
    top_products = df.groupby('Product')['Sales'].sum().sort_values(ascending=False).head(10)

    plt.figure()
    top_products.plot(kind='bar')
    plt.title("Top 10 Products by Sales")
    plt.xlabel("Product")
    plt.ylabel("Sales")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig("top_products.png")
    plt.close()

# Monthly Sales Chart
if 'Month' in df.columns:
    monthly_sales = df.groupby('Month')['Sales'].sum()

    plt.figure()
    monthly_sales.plot()
    plt.title("Monthly Sales Trend")
    plt.xlabel("Month")
    plt.ylabel("Sales")
    plt.tight_layout()
    plt.savefig("monthly_sales.png")
    plt.close()